<!--+page.svelte for the cities/[id] route-->
<script lang="ts">
	// 1. Import the PageData type definition generated by SvelteKit for type-safe page data
	import type { PageData } from './$types';
	import type {City} from '$lib/models/city.interface';

	// 2. Destructure the data prop with TypeScript type annotation to access page data loaded from +page.ts
	let { data }: { data: PageData } = $props();

	// 3. Create a reactive variable for the city object, derived from the loaded page data
	const city: City | undefined = $derived(data.city);
</script>

<!--UI: City data.-->
<div class="container mt-4">
	{#if city}
		<div class="card">
			<div class="card-header">
				<h3>City Details</h3>
				<div>This page is using the <code>load()</code> function to fetch <em>on the server</em>, instead of fetching on the client. </div>
				<div>See the <code>/cities/[id]/+page.ts</code> file in the source code tree for more details.</div>
			</div>
			<div class="card-body">
				<p><strong>ID:</strong> {city.id}</p>
				<p><strong>Name:</strong> {city.name}</p>
				<p><strong>Email:</strong> {city.country}</p>
			</div>
			<div class="card-footer">
				<a href="/cities" class="btn btn-secondary">Back to List</a>
			</div>
		</div>
	{:else}
		<!--		Make sure to have a fallback, if someone tries to access a non-existing customer.-->
		<div class="alert alert-danger">
			City not found.
			<div class="mt-2">
				<a href="/customers" class="btn btn-outline-danger">Back to List</a>
			</div>
		</div>
	{/if}
</div>
